In [ ]:
import pandas as pd

In [ ]:
from datasets import load_dataset

In [ ]:
data = load_dataset("roneneldan/TinyStories")

README.md:   0%|          | 0.00/1.06k [00:00<?, ?B/s]

data/train-00000-of-00004-2d5a1467fff108(…): reconstructing file:   0%|          |  0.00B /  249MB            

data/train-00000-of-00004-2d5a1467fff108(…): downloading bytes:           |  0.00B            

data/train-00001-of-00004-5852b56a2bd28f(…): reconstructing file:   0%|          |  0.00B /  248MB            

data/train-00001-of-00004-5852b56a2bd28f(…): downloading bytes:           |  0.00B            

data/train-00002-of-00004-a26307300439e9(…): reconstructing file:   0%|          |  0.00B /  246MB            

data/train-00002-of-00004-a26307300439e9(…): downloading bytes:           |  0.00B            

data/train-00003-of-00004-d243063613e5a0(…): reconstructing file:   0%|          |  0.00B /  248MB            

data/train-00003-of-00004-d243063613e5a0(…): downloading bytes:           |  0.00B            

data/validation-00000-of-00001-869c898b5(…): reconstructing file:   0%|          |  0.00B / 9.99MB            

data/validation-00000-of-00001-869c898b5(…): downloading bytes:           |  0.00B            

Generating train split:   0%|          | 0/2119719 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/21990 [00:00<?, ? examples/s]

In [ ]:
print(data)

DatasetDict({
    train: Dataset({
        features: ['text'],
        num_rows: 2119719
    })
    validation: Dataset({
        features: ['text'],
        num_rows: 21990
    })
})


In [ ]:
data['train']

Dataset({
    features: ['text'],
    num_rows: 2119719
})

In [ ]:
df = data['train'][0:500]

In [ ]:
df = pd.DataFrame(df)

In [ ]:
df

,text
0,"One day, a little girl named Lily found a need..."
1,"Once upon a time, there was a little car named..."
2,"One day, a little fish named Fin was swimming ..."
3,"Once upon a time, in a land full of trees, the..."
4,"Once upon a time, there was a little girl name..."
...,...
495,One day it was raining. The rain was cold and ...
496,"Once upon a time, a little girl lived in a big..."
497,Once there was a thin girl named Claire. Clair...
498,Once upon a time there was a boy. He liked to ...


In [ ]:
df = df[:1500]

In [ ]:
df

,text
0,"One day, a little girl named Lily found a need..."
1,"Once upon a time, there was a little car named..."
2,"One day, a little fish named Fin was swimming ..."
3,"Once upon a time, in a land full of trees, the..."
4,"Once upon a time, there was a little girl name..."
...,...
495,One day it was raining. The rain was cold and ...
496,"Once upon a time, a little girl lived in a big..."
497,Once there was a thin girl named Claire. Clair...
498,Once upon a time there was a boy. He liked to ...


In [ ]:
text = ""
for i in df['text']:
  text = text+i

In [ ]:
text

'One day, a little girl named Lily found a needle in her room. She knew it was difficult to play with it because it was sharp. Lily wanted to share the needle with her mom, so she could sew a button on her shirt.\n\nLily went to her mom and said, "Mom, I found this needle. Can you share it with me and sew my shirt?" Her mom smiled and said, "Yes, Lily, we can share the needle and fix your shirt."\n\nTogether, they shared the needle and sewed the button on Lily\'s shirt. It was not difficult for them because they were sharing and helping each other. After they finished, Lily thanked her mom for sharing the needle and fixing her shirt. They both felt happy because they had shared and worked together.Once upon a time, there was a little car named Beep. Beep loved to go fast and play in the sun. Beep was a healthy car because he always had good fuel. Good fuel made Beep happy and strong.\n\nOne day, Beep was driving in the park when he saw a big tree. The tree had many leaves that were fal

In [ ]:
with open('stories.txt','w') as file:
  file.write(text)

Data Preprocessing

In [ ]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split

In [ ]:
with open('stories.txt','r') as file:
  data =file.read().lower()

In [ ]:
data

'one day, a little girl named lily found a needle in her room. she knew it was difficult to play with it because it was sharp. lily wanted to share the needle with her mom, so she could sew a button on her shirt.\n\nlily went to her mom and said, "mom, i found this needle. can you share it with me and sew my shirt?" her mom smiled and said, "yes, lily, we can share the needle and fix your shirt."\n\ntogether, they shared the needle and sewed the button on lily\'s shirt. it was not difficult for them because they were sharing and helping each other. after they finished, lily thanked her mom for sharing the needle and fixing her shirt. they both felt happy because they had shared and worked together.once upon a time, there was a little car named beep. beep loved to go fast and play in the sun. beep was a healthy car because he always had good fuel. good fuel made beep happy and strong.\n\none day, beep was driving in the park when he saw a big tree. the tree had many leaves that were fal

Tokenize the text

In [ ]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts([text])
total_words = len(tokenizer.word_index)+1
total_words

3554

In [ ]:
tokenizer.word_index

{'the': 1,
 'and': 2,
 'to': 3,
 'a': 4,
 'was': 5,
 'he': 6,
 'she': 7,
 'it': 8,
 'her': 9,
 'so': 10,
 'in': 11,
 'said': 12,
 'they': 13,
 'of': 14,
 'his': 15,
 'that': 16,
 'day': 17,
 'had': 18,
 'with': 19,
 'little': 20,
 'there': 21,
 'time': 22,
 'but': 23,
 'one': 24,
 'you': 25,
 'very': 26,
 'girl': 27,
 'on': 28,
 'for': 29,
 'once': 30,
 'happy': 31,
 'were': 32,
 'saw': 33,
 'upon': 34,
 'big': 35,
 'all': 36,
 'up': 37,
 'when': 38,
 'wanted': 39,
 'i': 40,
 'then': 41,
 'smiled': 42,
 'him': 43,
 'went': 44,
 'around': 45,
 'mom': 46,
 'be': 47,
 'at': 48,
 'friends': 49,
 'boy': 50,
 'as': 51,
 'out': 52,
 'would': 53,
 'looked': 54,
 'from': 55,
 'something': 56,
 'go': 57,
 'could': 58,
 'back': 59,
 'asked': 60,
 'started': 61,
 'excited': 62,
 'ran': 63,
 'jack': 64,
 'what': 65,
 'can': 66,
 'play': 67,
 'together': 68,
 'felt': 69,
 'help': 70,
 'too': 71,
 'away': 72,
 'old': 73,
 'home': 74,
 'fun': 75,
 'have': 76,
 'found': 77,
 'who': 78,
 'loved': 79,
 '

Create input sequences

In [ ]:
input_sequences = []
for line in text.split('.'):
    token_list = tokenizer.texts_to_sequences([line])[0]
    for i in range(1,len(token_list)):
        n_gram_sequence = token_list[:i+1]
        input_sequences.append(n_gram_sequence)

In [ ]:
input_sequences

[[24, 17],
 [24, 17, 4],
 [24, 17, 4, 20],
 [24, 17, 4, 20, 27],
 [24, 17, 4, 20, 27, 84],
 [24, 17, 4, 20, 27, 84, 157],
 [24, 17, 4, 20, 27, 84, 157, 77],
 [24, 17, 4, 20, 27, 84, 157, 77, 4],
 [24, 17, 4, 20, 27, 84, 157, 77, 4, 1053],
 [24, 17, 4, 20, 27, 84, 157, 77, 4, 1053, 11],
 [24, 17, 4, 20, 27, 84, 157, 77, 4, 1053, 11, 9],
 [24, 17, 4, 20, 27, 84, 157, 77, 4, 1053, 11, 9, 199],
 [7, 127],
 [7, 127, 8],
 [7, 127, 8, 5],
 [7, 127, 8, 5, 1054],
 [7, 127, 8, 5, 1054, 3],
 [7, 127, 8, 5, 1054, 3, 67],
 [7, 127, 8, 5, 1054, 3, 67, 19],
 [7, 127, 8, 5, 1054, 3, 67, 19, 8],
 [7, 127, 8, 5, 1054, 3, 67, 19, 8, 200],
 [7, 127, 8, 5, 1054, 3, 67, 19, 8, 200, 8],
 [7, 127, 8, 5, 1054, 3, 67, 19, 8, 200, 8, 5],
 [7, 127, 8, 5, 1054, 3, 67, 19, 8, 200, 8, 5, 1177],
 [157, 39],
 [157, 39, 3],
 [157, 39, 3, 304],
 [157, 39, 3, 304, 1],
 [157, 39, 3, 304, 1, 1053],
 [157, 39, 3, 304, 1, 1053, 19],
 [157, 39, 3, 304, 1, 1053, 19, 9],
 [157, 39, 3, 304, 1, 1053, 19, 9, 46],
 [157, 39, 3, 304

padding

In [ ]:
max_sequence_len = max([len(i) for i in input_sequences])
max_sequence_len

94

In [ ]:
input_sequences = np.array(pad_sequences(input_sequences,maxlen=max_sequence_len,padding='pre'))
input_sequences.shape

(71052, 94)

Train test Split

In [ ]:
X,y = input_sequences[:,:-1],input_sequences[:,-1]

In [ ]:
X

array([[  0,   0,   0, ...,   0,   0,  24],
       [  0,   0,   0, ...,   0,  24,  17],
       [  0,   0,   0, ...,  24,  17,   4],
       ...,
       [  0,   0,   0, ...,   6,  53,  98],
       [  0,   0,   0, ...,  53,  98,  47],
       [  0,   0,   0, ...,  98,  47, 575]], dtype=int32)

In [ ]:
y

array([ 17,   4,  20, ...,  47, 575,  82], dtype=int32)

In [ ]:
import tensorflow as tf

In [ ]:
y = tf.keras.utils.to_categorical(y,num_classes=total_words)

In [ ]:
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

Model Building

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense,Dropout,Input

Define the model

In [ ]:
model = Sequential()
model.add(Input(shape=(max_sequence_len,)))
model.add(Embedding(input_dim=total_words,output_dim=100))
model.add(LSTM(150,return_sequences=True))
model.add(Dropout(0.2))
model.add(LSTM(100))
model.add(Dense(total_words,activation='softmax'))


compile the model

In [ ]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 94, 100)        │       355,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 94, 150)        │       150,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 94, 150)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ (None, 100)            │       100,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 3554)           │       358,954 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 965,354 (3.68 MB)

 Trainable params: 965,354 (3.68 MB)

 Non-trainable params: 0 (0.00 B)

Train the model

In [ ]:
history = model.fit(X_train,y_train,epochs=50,validation_data=(X_test,y_test),verbose=1)

Epoch 1/50
1777/1777 ━━━━━━━━━━━━━━━━━━━━ 31s 16ms/step - accuracy: 0.3309 - loss: 3.0676 - val_accuracy: 0.2438 - val_loss: 5.5973
Epoch 2/50
1777/1777 ━━━━━━━━━━━━━━━━━━━━ 30s 17ms/step - accuracy: 0.3415 - loss: 2.9361 - val_accuracy: 0.2440 - val_loss: 5.6513
Epoch 3/50
1777/1777 ━━━━━━━━━━━━━━━━━━━━ 30s 17ms/step - accuracy: 0.3485 - loss: 2.8793 - val_accuracy: 0.2454 - val_loss: 5.7207
Epoch 4/50
1777/1777 ━━━━━━━━━━━━━━━━━━━━ 29s 16ms/step - accuracy: 0.3552 - loss: 2.8447 - val_accuracy: 0.2400 - val_loss: 5.7817
Epoch 5/50
1777/1777 ━━━━━━━━━━━━━━━━━━━━ 30s 17ms/step - accuracy: 0.3604 - loss: 2.8086 - val_accuracy: 0.2402 - val_loss: 5.8372
Epoch 6/50
1777/1777 ━━━━━━━━━━━━━━━━━━━━ 29s 16ms/step - accuracy: 0.3630 - loss: 2.7798 - val_accuracy: 0.2422 - val_loss: 5.8967
Epoch 7/50
1777/1777 ━━━━━━━━━━━━━━━━━━━━ 29s 16ms/step - accuracy: 0.3684 - loss: 2.7428 - val_accuracy: 0.2418 - val_loss: 5.9230
Epoch 8/50
1777/1777 ━━━━━━━━━━━━━━━━━━━━ 28s 16ms/step - accuracy: 0.3738 -

In [ ]:
def predict_next_word(model,tokenizer,text,max_sequence_len):
  token_list = tokenizer.texts_to_sequences([text])[0]
  if len(token_list) >= max_sequence_len:
    token_list = token_list[-(max_sequence_len):]
  token_list = pad_sequences([token_list], maxlen=max_sequence_len,padding='pre')
  predicted = model.predict(token_list,verbose=0)
  predicted_word_index = np.argmax(predicted,axis=1)
  for word, index in tokenizer.word_index.items():
    if index == predicted_word_index:
      return word
  return None

In [ ]:
input_text = "Who is enough for her mum who are you going to touch"
print(f"Input text : {input_text}")
max_sequence_len = model.input_shape[1]+1
next_word = predict_next_word(model,tokenizer,input_text,max_sequence_len)
print(f"Next word : {next_word}")

Input text : Who is enough for her mum who are you going to touch
Next word : the


Save the model

In [ ]:
model.save('next_word_predictor_lstm.h5')

Save tokenizer

In [ ]:
import pickle
with open('tokenizer.pickle','wb') as handle:
  pickle.dump(tokenizer,handle,protocol=pickle.HIGHEST_PROTOCOL)